%% Import data from text file.
% Script for importing data from the following text file:
%
%    ..\ExpData.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2019/08/09 14:39:06

%% 从文件对话框选取导入的数据文件
[File, PathName] = uigetfile('*.*', '实验数据结果txt文件 ...', 'Multiselect', 'off');
if isequal(File,0)
    filename = 'ExpData.txt';
    fprintf('User selected cancel and use default %s file.\n', filename)
else
    filename = [PathName,File];
    fprintf('Selected %s file to import\n', filename)
end

%% Initialize variables.
delimiter = '\t';
startRow = 3;

%% Format string for each line of text:
%   column1 - U: double (%f)
%	column2 - I: double (%f)
%   column3 - T(1): double (%f)
%	column4 - T(2): double (%f)
%   column5 - Q(1): double (%f)
%	column6 - Q(2): double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
ExpData = table(dataArray{1:end-1}, 'VariableNames', {'U','I','TH','TC','QH','QC'});

%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;